global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'payment-service'
    static_configs:
      - targets: [ 'payment-service:8080' ]

  - job_name: 'order-service'
    static_configs:
      - targets: ['order-service:8081']